version: "3"
services:
  postgres:
    container_name: micro-orm-postgres
    image: "postgres:latest"
    ports:
      - "5432:${DATABASE_PORT:-5432}"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-test}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-test}
      POSTGRES_DB: ${DATABASE_NAME:-test}
